#!/usr/bin/env bash
# Install caveman toolkit for VS Code Copilot, GitHub Copilot CLI, and OpenCode.
#
# Instructions -> VS Code user prompts folder (auto-load by file type)
# Agents -> ~/.copilot/agents/ (shared by VS Code and Copilot CLI)
# Instructions -> ~/.copilot/copilot-instructions.md (merged, for CLI)
# Agent -> ~/.config/opencode/agents/ (global for OpenCode)
# Instructions -> ~/.config/opencode/AGENTS.md (merged, for OpenCode)
#
# VS Code reads both its prompts folder AND ~/.copilot/agents/, so agents
# are installed once to ~/.copilot/agents/ to avoid duplicates.
#
# Usage:
#   ./install.sh              # Install for VS Code, Copilot CLI, and OpenCode
#   ./install.sh vscode       # VS Code only
#   ./install.sh cli          # Copilot CLI only
#   ./install.sh opencode     # OpenCode only
#   ./install.sh project      # Regenerate repo-level AGENTS.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTRUCTIONS_DIR="$SCRIPT_DIR/instructions"

# Detect VS Code prompts folder
if [[ "$OSTYPE" == darwin* ]]; then
    VSCODE_PROMPTS="$HOME/Library/Application Support/Code/User/prompts"
else
    VSCODE_PROMPTS="${XDG_CONFIG_HOME:-$HOME/.config}/Code/User/prompts"
fi

COPILOT_DIR="$HOME/.copilot"
COPILOT_AGENTS_DIR="$COPILOT_DIR/agents"
COPILOT_INSTRUCTIONS="$COPILOT_DIR/copilot-instructions.md"

install_vscode() {
    echo "==> Installing for VS Code Copilot..."

    mkdir -p "$VSCODE_PROMPTS"

    # Clean up stale files from previous installs
    rm -f "$VSCODE_PROMPTS/caveman.agent.md"
    rm -f "$VSCODE_PROMPTS/anvil.agent.md"
    rm -f "$VSCODE_PROMPTS/caveman-review.prompt.md"

    # Instructions (agents are installed via install_cli to ~/.copilot/agents/)
    for f in "$INSTRUCTIONS_DIR"/*.instructions.md; do
        [ -f "$f" ] || continue
        cp "$f" "$VSCODE_PROMPTS/"
        echo "    Copied $(basename "$f")"
    done

    echo "==> VS Code install complete ($VSCODE_PROMPTS)"
}

install_cli() {
    echo "==> Installing for GitHub Copilot CLI..."

    mkdir -p "$COPILOT_DIR"
    mkdir -p "$COPILOT_AGENTS_DIR"

    # Clean up stale files from previous installs
    rm -f "$COPILOT_AGENTS_DIR/caveman.md"

    # --- Agents → ~/.copilot/agents/ (convert frontmatter for CLI) ---
    for f in "$SCRIPT_DIR"/*.agent.md; do
        [ -f "$f" ] || continue
        name="$(basename "$f" .agent.md)"
        # Extract name + description from frontmatter, drop VS Code-only fields
        {
            echo '---'
            sed -n '/^---$/,/^---$/p' "$f" | sed '1d;$d' | grep -E '^(name|description)\s*:'
            echo '---'
            echo ''
            # Body after frontmatter
            sed '1{/^---$/!b end};/^---$/,/^---$/d;:end' "$f" | sed '/./,$!d'
        } > "$COPILOT_AGENTS_DIR/$name.md"
        echo "    Installed agent: $name ($COPILOT_AGENTS_DIR/$name.md)"
    done

    # --- Instructions → ~/.copilot/copilot-instructions.md (merged) ---
    {
        cat <<'HEADER'
# Copilot CLI Global Instructions
# Auto-generated by caveman install script.
# Source: https://github.com/<owner>/caveman
# Do not edit manually — re-run install.sh to update.

HEADER
        count=0
        for f in "$INSTRUCTIONS_DIR"/*.instructions.md; do
            [ -f "$f" ] || continue
            name="$(basename "$f" .instructions.md)"
            echo "# === $name ==="
            echo ""
            # Strip YAML frontmatter (--- ... ---)
            sed '1{/^---$/!b end};/^---$/,/^---$/d;:end' "$f"
            echo ""
            echo ""
            count=$((count + 1))
        done
        echo "# $count instruction files merged."
    } > "$COPILOT_INSTRUCTIONS"

    echo "    Wrote $COPILOT_INSTRUCTIONS"
    echo "==> Copilot CLI install complete"
    echo ""
    echo "    Agents in ~/.copilot/agents/ (shared by VS Code and CLI)"
    echo "    Instructions loaded globally for all sessions."
}

OPENCODE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/opencode"
OPENCODE_AGENTS_DIR="$OPENCODE_DIR/agents"
OPENCODE_AGENTS="$OPENCODE_DIR/AGENTS.md"

install_opencode() {
    echo "==> Installing for OpenCode..."

    mkdir -p "$OPENCODE_DIR"
    mkdir -p "$OPENCODE_AGENTS_DIR"

    # --- Agent -> ~/.config/opencode/agents/ (convert to OpenCode frontmatter) ---
    for f in "$SCRIPT_DIR"/*.agent.md; do
        [ -f "$f" ] || continue
        name="$(basename "$f" .agent.md)"
        # Extract description from VS Code frontmatter
        desc="$(sed -n '/^---$/,/^---$/p' "$f" | sed '1d;$d' | grep -E '^description\s*:' | sed 's/^description:\s*//')"
        # Build OpenCode frontmatter + body
        {
            echo '---'
            echo "description: $desc"
            echo 'mode: primary'
            echo 'permission:'
            echo '  edit: allow'
            echo '  bash: allow'
            echo '---'
            echo ''
            # Body after frontmatter
            sed '1{/^---$/!b end};/^---$/,/^---$/d;:end' "$f" | sed '/./,$!d'
        } > "$OPENCODE_AGENTS_DIR/$name.md"
        echo "    Installed agent: $name ($OPENCODE_AGENTS_DIR/$name.md)"
    done

    # --- Instructions -> ~/.config/opencode/AGENTS.md (merged) ---
    {
        cat <<'HEADER'
# OpenCode Global Instructions
# Auto-generated by caveman install script.
# Source: https://github.com/<owner>/caveman
# Do not edit manually — re-run install.sh to update.

HEADER
        count=0
        for f in "$INSTRUCTIONS_DIR"/*.instructions.md; do
            [ -f "$f" ] || continue
            name="$(basename "$f" .instructions.md)"
            echo "# === $name ==="
            echo ""
            # Strip YAML frontmatter (--- ... ---)
            sed '1{/^---$/!b end};/^---$/,/^---$/d;:end' "$f"
            echo ""
            echo ""
            count=$((count + 1))
        done
        echo "# $count instruction files merged."
    } > "$OPENCODE_AGENTS"

    echo "    Wrote $OPENCODE_AGENTS"
    echo "==> OpenCode install complete"
    echo ""
    echo "    Agent in ~/.config/opencode/agents/ (global for all projects)"
    echo "    Instructions in ~/.config/opencode/AGENTS.md"
}

install_project() {
    echo "==> Generating project-level AGENTS.md..."

    dest="$SCRIPT_DIR/AGENTS.md"
    {
        cat <<'HEADER'
# AGENTS.md
# Auto-generated by caveman install script.
# Source: https://github.com/wgelard/caveman-agent
# Do not edit manually — re-run: ./install.sh project
# Read by: OpenCode, Claude Code, Gemini CLI, and other AI coding tools.

HEADER
        count=0
        for f in "$INSTRUCTIONS_DIR"/*.instructions.md; do
            [ -f "$f" ] || continue
            name="$(basename "$f" .instructions.md)"
            echo "# === $name ==="
            echo ""
            # Strip YAML frontmatter (--- ... ---)
            sed '1{/^---$/!b end};/^---$/,/^---$/d;:end' "$f"
            echo ""
            echo ""
            count=$((count + 1))
        done
        echo "# $count instruction files merged."
    } > "$dest"

    echo "    Wrote $dest"
    echo "==> Project AGENTS.md generated"
}

# --- Main ---
echo ""
echo "caveman installer"
echo ""

target="${1:-all}"
case "$target" in
    vscode)   install_vscode ;;
    cli)      install_cli ;;
    opencode) install_opencode ;;
    project)  install_project ;;
    all)      install_vscode; echo ""; install_cli; echo ""; install_opencode; echo ""; install_project ;;
    *)        echo "Usage: $0 [all|vscode|cli|opencode|project]"; exit 1 ;;
esac

# Run verification
echo ""
bash "$(dirname "$0")/test-install.sh" present

echo ""
