<#
.SYNOPSIS
    Install caveman toolkit for VS Code Copilot and GitHub Copilot CLI.

.DESCRIPTION
    Copies files to the appropriate locations:
    - Instructions -> VS Code user prompts folder (auto-load by file type)
    - Agents -> ~/.copilot/agents/ (shared by VS Code and Copilot CLI)
    - Instructions -> ~/.copilot/copilot-instructions.md (merged, for CLI)

    VS Code reads both its prompts folder AND ~/.copilot/agents/, so agents
    are installed once to ~/.copilot/agents/ to avoid duplicates.

.PARAMETER Target
    Installation target: 'all' (default), 'vscode', or 'cli'.

.EXAMPLE
    .\install.ps1              # Install for both VS Code and Copilot CLI
    .\install.ps1 -Target vscode  # VS Code only
    .\install.ps1 -Target cli     # Copilot CLI only
#>
[CmdletBinding()]
param(
    [ValidateSet('all', 'vscode', 'cli')]
    [string]$Target = 'all'
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

# --- Paths ---
$VscodePrompts = Join-Path $env:APPDATA 'Code\User\prompts'
$CopilotDir = Join-Path $HOME '.copilot'
$CopilotAgentsDir = Join-Path $CopilotDir 'agents'
$CopilotInstructions = Join-Path $CopilotDir 'copilot-instructions.md'
$InstructionsDir = Join-Path $ScriptDir 'instructions'

function Install-VsCode {
    Write-Host '==> Installing for VS Code Copilot...' -ForegroundColor Cyan

    if (-not (Test-Path $VscodePrompts)) {
        New-Item -ItemType Directory -Path $VscodePrompts -Force | Out-Null
        Write-Host "    Created $VscodePrompts"
    }

    # Clean up stale files from previous installs
    foreach ($stale in @('caveman.agent.md', 'anvil.agent.md', 'caveman-review.prompt.md')) {
        $stalePath = Join-Path $VscodePrompts $stale
        if (Test-Path $stalePath) {
            Remove-Item $stalePath -Force
            Write-Host "    Removed stale $stale"
        }
    }

    # Instructions (agents are installed via Install-Cli to ~/.copilot/agents/)
    $instructions = Get-ChildItem -Path $InstructionsDir -Filter '*.instructions.md'
    foreach ($f in $instructions) {
        Copy-Item $f.FullName -Destination $VscodePrompts -Force
        Write-Host "    Copied $($f.Name)"
    }

    Write-Host "==> VS Code install complete ($VscodePrompts)" -ForegroundColor Green
}

function Install-Cli {
    Write-Host '==> Installing for GitHub Copilot CLI...' -ForegroundColor Cyan

    if (-not (Test-Path $CopilotDir)) {
        New-Item -ItemType Directory -Path $CopilotDir -Force | Out-Null
        Write-Host "    Created $CopilotDir"
    }

    # --- Agents → ~/.copilot/agents/ (strip VS Code frontmatter) ---
    if (-not (Test-Path $CopilotAgentsDir)) {
        New-Item -ItemType Directory -Path $CopilotAgentsDir -Force | Out-Null
    }

    # Clean up stale files from previous installs
    Remove-Item (Join-Path $CopilotAgentsDir 'caveman.md') -ErrorAction SilentlyContinue

    $agents = Get-ChildItem -Path $ScriptDir -Filter '*.agent.md'
    foreach ($f in $agents) {
        $content = Get-Content $f.FullName -Raw
        # Convert frontmatter: keep name + description, drop VS Code-only fields
        if ($content -match '(?s)^---\r?\n(.*?)\r?\n---\r?\n(.*)$') {
            $frontmatter = $Matches[1]
            $body = $Matches[2]
            $cliYaml = @()
            foreach ($line in ($frontmatter -split '\r?\n')) {
                if ($line -match '^(name|description)\s*:') {
                    $cliYaml += $line
                }
            }
            $content = "---`n$($cliYaml -join "`n")`n---`n`n$body"
        }
        $cliName = $f.BaseName -replace '\.agent$', ''
        $destPath = Join-Path $CopilotAgentsDir "$cliName.md"
        Set-Content -Path $destPath -Value $content -Encoding utf8NoBOM
        Write-Host "    Installed agent: $cliName ($destPath)"
    }

    # --- Instructions → ~/.copilot/copilot-instructions.md (merged) ---
    $header = @"
# Copilot CLI Global Instructions
# Auto-generated by caveman install script.
# Source: https://github.com/<owner>/caveman
# Do not edit manually — re-run install.ps1 to update.

"@

    $instructions = Get-ChildItem -Path $InstructionsDir -Filter '*.instructions.md'
    $body = foreach ($f in $instructions) {
        $content = Get-Content $f.FullName -Raw
        # Strip YAML frontmatter
        $content = $content -replace '(?s)^---\r?\n.*?\r?\n---\r?\n', ''
        "# === $($f.BaseName -replace '\.instructions$','') ===`n`n$content"
    }

    $output = $header + ($body -join "`n`n")
    Set-Content -Path $CopilotInstructions -Value $output -Encoding utf8NoBOM
    Write-Host "    Wrote $CopilotInstructions ($($instructions.Count) instruction files merged)"

    Write-Host '==> Copilot CLI install complete' -ForegroundColor Green
    Write-Host ''
    Write-Host '    Agents in ~/.copilot/agents/ (shared by VS Code and CLI)' -ForegroundColor Yellow
    Write-Host '    Instructions loaded globally for all sessions.' -ForegroundColor Yellow
}

# --- Main ---
Write-Host ''
Write-Host 'caveman installer' -ForegroundColor White
Write-Host ''

switch ($Target) {
    'vscode' { Install-VsCode }
    'cli'    { Install-Cli }
    'all'    { Install-VsCode; Write-Host ''; Install-Cli }
}

# Run verification
Write-Host ''
& (Join-Path $ScriptDir 'test-install.ps1') -Expected present

Write-Host ''
