#!/usr/bin/env bash
# Install caveman-agent toolkit for VS Code Copilot and GitHub Copilot CLI.
#
# Usage:
#   ./install.sh              # Install for both VS Code and Copilot CLI
#   ./install.sh vscode       # VS Code only
#   ./install.sh cli          # Copilot CLI only
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTRUCTIONS_DIR="$SCRIPT_DIR/instructions"

# Detect VS Code prompts folder
if [[ "$OSTYPE" == darwin* ]]; then
    VSCODE_PROMPTS="$HOME/Library/Application Support/Code/User/prompts"
else
    VSCODE_PROMPTS="${XDG_CONFIG_HOME:-$HOME/.config}/Code/User/prompts"
fi

COPILOT_DIR="$HOME/.copilot"
COPILOT_AGENTS_DIR="$COPILOT_DIR/agents"
COPILOT_INSTRUCTIONS="$COPILOT_DIR/copilot-instructions.md"

install_vscode() {
    echo "==> Installing for VS Code Copilot..."

    mkdir -p "$VSCODE_PROMPTS"

    # Agents
    for f in "$SCRIPT_DIR"/*.agent.md; do
        [ -f "$f" ] || continue
        cp "$f" "$VSCODE_PROMPTS/"
        echo "    Copied $(basename "$f")"
    done

    # Prompts
    for f in "$SCRIPT_DIR"/*.prompt.md; do
        [ -f "$f" ] || continue
        cp "$f" "$VSCODE_PROMPTS/"
        echo "    Copied $(basename "$f")"
    done

    # Instructions
    for f in "$INSTRUCTIONS_DIR"/*.instructions.md; do
        [ -f "$f" ] || continue
        cp "$f" "$VSCODE_PROMPTS/"
        echo "    Copied $(basename "$f")"
    done

    echo "==> VS Code install complete ($VSCODE_PROMPTS)"
}

install_cli() {
    echo "==> Installing for GitHub Copilot CLI..."

    mkdir -p "$COPILOT_DIR"
    mkdir -p "$COPILOT_AGENTS_DIR"

    # --- Agents → ~/.copilot/agents/ (convert frontmatter for CLI) ---
    for f in "$SCRIPT_DIR"/*.agent.md; do
        [ -f "$f" ] || continue
        name="$(basename "$f" .agent.md)"
        # Extract name + description from frontmatter, drop VS Code-only fields
        {
            echo '---'
            sed -n '/^---$/,/^---$/p' "$f" | sed '1d;$d' | grep -E '^(name|description)\s*:'
            echo '---'
            echo ''
            # Body after frontmatter
            sed '1{/^---$/!b end};/^---$/,/^---$/d;:end' "$f" | sed '/./,$!d'
        } > "$COPILOT_AGENTS_DIR/$name.md"
        echo "    Installed agent: $name ($COPILOT_AGENTS_DIR/$name.md)"
    done

    # --- Instructions → ~/.copilot/copilot-instructions.md (merged) ---
    {
        cat <<'HEADER'
# Copilot CLI Global Instructions
# Auto-generated by caveman-agent install script.
# Source: https://github.com/<owner>/caveman-agent
# Do not edit manually — re-run install.sh to update.

HEADER
        count=0
        for f in "$INSTRUCTIONS_DIR"/*.instructions.md; do
            [ -f "$f" ] || continue
            name="$(basename "$f" .instructions.md)"
            echo "# === $name ==="
            echo ""
            # Strip YAML frontmatter (--- ... ---)
            sed '1{/^---$/!b end};/^---$/,/^---$/d;:end' "$f"
            echo ""
            echo ""
            count=$((count + 1))
        done
        echo "# $count instruction files merged."
    } > "$COPILOT_INSTRUCTIONS"

    echo "    Wrote $COPILOT_INSTRUCTIONS"
    echo "==> Copilot CLI install complete"
    echo ""
    echo "    Agents available via /agent or copilot --agent=<name>"
    echo "    Instructions loaded globally for all sessions."
}

# --- Main ---
echo ""
echo "caveman-agent installer"
echo ""

target="${1:-all}"
case "$target" in
    vscode) install_vscode ;;
    cli)    install_cli ;;
    all)    install_vscode; echo ""; install_cli ;;
    *)      echo "Usage: $0 [all|vscode|cli]"; exit 1 ;;
esac

echo ""
